QuotesAppNet6/Models/Entities/Quote.cs
using Microsoft.Build.Framework;

namespace QuotesApp.Models.Entities;

public class Quote
{
    public int Id { get; set; }
    [Required]
    public string TheQuote { get; set; } = String.Empty;
    [Required]
    public string WhoSaidIt { get; set; } = String.Empty;
}

QuotesAppNet6/Models/ErrorViewModel.cs
namespace QuotesAppNet6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

QuotesAppNet6/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QuotesApp.Services;
using QuotesAppNet6.Models;
using System.Diagnostics;

namespace QuotesAppNet6.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IQuoteRepository _quoteRepo;

    public HomeController(IQuoteRepository quoteRepo, ILogger<HomeController> logger)
    {
        _logger = logger;
        _quoteRepo = quoteRepo;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _quoteRepo.ReadAllAsync());
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

QuotesAppNet6/Controllers/QuoteController.cs
using Microsoft.AspNetCore.Mvc;
using QuotesApp.Models.Entities;
using QuotesApp.Services;

namespace QuotesAppNet6.Controllers
{
    public class QuoteController : Controller
    {
        private readonly IQuoteRepository _quoteRepo;

        public QuoteController(IQuoteRepository quoteRepo)
        {
            _quoteRepo = quoteRepo;
        }
        [HttpPost]
        public async Task<IActionResult> CreateAjax(Quote quote)
        {
            if (ModelState.IsValid)
            {
                await _quoteRepo.CreateAsync(quote);
                return Json(new { quoteId = quote.Id, message = "success" });
            }
            return Json("fail");
        }
        public async Task<IActionResult> QuoteRow(int id)
        {
            var quote = await _quoteRepo.ReadAsync(id);
            return PartialView("/Views/Home/_QuoteRow.cshtml", quote);
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

QuotesAppNet6/Views/Home/Index.cshtml
@model IEnumerable<Quote>

<h1>My Favorite Quotes</h1>
<button type="button" class="btn btn-primary mb-3" id="btnCreateQuote">Create new</button>
<div id="alertArea" class="alert alert-info" role="alert" style="display:none">
    <span id="messageArea"></span>
</div>
<partial name="_CreateQuoteModal" model="@new Quote()">
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                The Quote
            </th>
            <th>
                Who Said It
            </th>
        </tr>
    </thead>
    <tbody id="tbody-quotes">
        @foreach (var item in Model)
        {
                <partial name="_QuoteRow" model="@item" />
        }
    </tbody>
</table>
@section Scripts{
    @{
            <script src="~/js/homeIndex.js"></script>
    }
    
}

QuotesAppNet6/Views/Home/_CreateQuoteModal.cshtml
@model Quote
<div class="modal fade" id="createQuoteModal" tabindex="-1" role="dialog" aria-labelledby="createPetModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div id="mainContent" class="modal-content">
            <form id="createQuoteForm" asp-controller="Quote" asp-action="Create">
                <div class="modal-header">
                    <h5 class="modalTitle" id="createPetModalTitle">
                        Create Quote
                    </h5>
                    <button type="button" class="btn-close"
                            data-bs-dismiss="modal" aria-label="Close">
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row mb-3">
                        <label class="col-sm-2 col-form-label">
                            TheQuote
                        </label>
                    <div class="col-sm-10">
                        <input asp-for="TheQuote" class="form-control"/>
                        <span asp-validation-for="TheQuote"></span>
                    </div>
                    </div>
                    <div class="form-group row mb-3">
                        <label class="col-sm-2 col-form-label">
                            WhoSaidIt
                        </label>
                        <div class="col-sm-10">
                        <input asp-for="WhoSaidIt" class="form-control" />
                        <span asp-validation-for="WhoSaidIt"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">
                        Save
                    </button>
                    <button type="reset" class="btn btn-secondary">Clear</button>
                </div>
            </form>
        </div>
    </div>
</div>

QuotesAppNet6/Views/Home/_QuoteRow.cshtml
@model Quote
<tr id="row-@Model.Id">
    <td>
        @Html.DisplayFor(modelItem => Model.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.TheQuote)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.WhoSaidIt)
    </td>
</tr>

QuotesAppNet6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuotesAppNet6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuotesAppNet6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QuotesAppNet6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - QuotesAppNet6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>